# Generated by Django 6.0.3 on 2026-04-03 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recordsapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='financialrecord',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
